=== acasi-ctf/ctf/challenges/schemas/challenge.schema.json
{
  "$id": "challenge-schema",
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "challenge",
  "description": "Describes high-level information for a challenge",
  "properties": {
    "$schema": {
    },
    "id": {
      "description": "UUID for this challenge, must be unique amongst other challenges",
      "type": "string",
      "format": "uuid",
      "pattern": "^[0-9a-fA-F]{8}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{12}$"
    },
    "slug": {
      "description": "URL-friendly name for this challenge, must be unique within a challenge set",
      "type": "string",
      "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
    },
    "name": {
      "description": "Human-facing name of the challenge",
      "type": "string"
    },
    "description": {
      "description": "Human-facing description of the challenge",
      "type": "string"
    },
    "provisioner": {
      "description": "Provisioner-backend that is used to create environments for this challenge",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "kubernetes"
          ]
        }
      },
      "required": [
        "type"
      ]
    },
    "documentation": {
      "description": "List of documentation pages for this challenge in order",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Short name to be used in the tab",
            "type": "string"
          },
          "path": {
            "description": "Path to the documentation in Markdown format",
            "type": "string"
          }
        },
        "required": [
          "name",
          "path"
        ]
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "id",
    "slug",
    "name",
    "description",
    "provisioner",
    "documentation"
  ]
}

=== acasi-ctf/ctf/challenges/pentesting/challenges/hashcat/challenge.json
{
  "$schema": "../../../schemas/challenge.schema.json",
  "id": "4c80e73e-c22c-4be2-ab9b-bb29009fca60",
  "slug": "hashcat",
  "name": "hashcat",
  "description": "This is a challenge that demonstrates hashcat tool",
  "provisioner": {
    "type": "kubernetes"
  },
  "documentation": [
    {
      "name": "HashcatDocumentation",
      "path": "docs/HashcatDocumentation.md"
    }
  ]
}

=== acasi-ctf/ctf/challenges/kali/challenges/intro/challenge.json
{
  "$schema": "../../../schemas/challenge.schema.json",
  "id": "9efea081-241e-4d0f-b0ec-3bd8237db217",
  "slug": "intro",
  "name": "Introduction",
  "description": "This is a challenge that demonstrates introductory tools",
  "provisioner": {
    "type": "kubernetes"
  },
  "documentation": [
    {
      "name": "StringsDocument",
      "path": "docs/StringsDocument.md"
    }
  ]
}

=== acasi-ctf/ctf/challenges/games/challenges/rock-paper-scissors/challenge.json
{
  "$schema": "../../../schemas/challenge.schema.json",
  "id": "e6ddf451-e5e6-423a-bcd0-6841d738d421",
  "slug": "rock-paper-scissors",
  "name": "Rock Paper Scissors",
  "description": "Game of Rock Paper Scissors",
  "provisioner": {
    "type": "kubernetes"
  },
  "documentation": [
    {
      "name": "RockPaperScissors",
      "path": "docs/RockPaperScissors.md"
    }
  ]
}

=== acasi-ctf/ctf/challenges/games/challenges/yahtzee/challenge.json
{
  "$schema": "../../../schemas/challenge.schema.json",
  "id": "e0867c69-92cd-4e50-b23b-b782ec3e251f",
  "slug": "yahtzee",
  "name": "Yahtzee",
  "description": "Game of Yahtzee",
  "provisioner": {
    "type": "kubernetes"
  },
  "documentation": [
    {
      "name": "Yahtzee",
      "path": "docs/Yahtzee.md"
    }
  ]
}

=== acasi-ctf/ctf/challenges/kali/challenges/strings/challenge.json
{
  "$schema": "../../../schemas/challenge.schema.json",
  "id": "9efea081-241e-4d0f-b0ec-3bd8237db217",
  "slug": "strings",
  "name": "strings",
  "description": "This is a challenge that demonstrates strings tool",
  "provisioner": {
    "type": "kubernetes"
  },
  "documentation": [
    {
      "name": "StringsDocument",
      "path": "docs/StringsDocument.md"
    }
  ]
}

=== acasi-ctf/ctf/challenges/ciphers/challenges/caesar-cipher/challenge.json
{
  "$schema": "../../../schemas/challenge.schema.json",
  "id": "737ca46c-c31d-4e32-9702-e18a691b8641",
  "slug": "caesar-cipher",
  "name": "Caesar Cipher",
  "description": "This is a challenge that demonstrates caesar cipher",
  "provisioner": {
    "type": "kubernetes"
  },
  "documentation": [
    {
      "name": "Cryptography",
      "path": "docs/1-Cryptography.md"
    },
    {
      "name": "Caesar cipher",
      "path": "docs/Caesar-cipher.md"
    },
    {
      "name": "Terminal Usage",
      "path": "docs/Terminal_Use.md"
    }
  ]
}

=== acasi-ctf/ctf/challenges/internal/challenges/sqlinjection/challenge.json
{
  "$schema": "../../../schemas/challenge.schema.json",
  "id": "d927f959-67aa-4e4b-8da2-f65ed17fa915",
  "slug": "sqlinjection",
  "name": "SQL Injection Example",
  "description": "This is an example challenge to demonstrate web environments",
  "provisioner": {
    "type": "kubernetes"
  },
  "documentation": []
}

=== acasi-ctf/ctf/ui/src/challenges/example/challenges/basic-env-example/challenge.json
{
  "$schema": "../../../schemas/challenge.schema.json",
  "id": "f332ab2e-6b10-42e6-8c54-6902f0dc01a4",
  "slug": "example-challenge",
  "name": "Basic Environment Example",
  "description": "This is an example challenge to demonstrate basic environments",
  "provisioner": {
    "type": "kubernetes"
  },
  "documentation": [
    {
      "name": "Hello 1",
      "path": "docs/Hello1.md"
    },
    {
      "name": "Hello 2",
      "path": "docs/Hello2.md"
    },
    {
      "name": "Hello 3",
      "path": "docs/Hello3.md"
    }
  ]
}
