=== acasi-ctf/ctf/challenges/schemas/challenge.schema.json
{
  "$id": "challenge-schema",
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "challenge",
  "description": "Describes high-level information for a challenge",
  "properties": {
    "$schema": {
    },
    "id": {
      "description": "UUID for this challenge, must be unique amongst other challenges",
      "type": "string",
      "format": "uuid",
      "pattern": "^[0-9a-fA-F]{8}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{12}$"
    },
    "slug": {
      "description": "URL-friendly name for this challenge, must be unique within a challenge set",
      "type": "string",
      "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
    },
    "name": {
      "description": "Human-facing name of the challenge",
      "type": "string"
    },
    "description": {
      "description": "Human-facing description of the challenge",
      "type": "string"
    },
    "provisioner": {
      "description": "Provisioner-backend that is used to create environments for this challenge",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "kubernetes"
          ]
        }
      },
      "required": [
        "type"
      ]
    },
    "documentation": {
      "description": "List of documentation pages for this challenge in order",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Short name to be used in the tab",
            "type": "string"
          },
          "path": {
            "description": "Path to the documentation in Markdown format",
            "type": "string"
          }
        },
        "required": [
          "name",
          "path"
        ]
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "id",
    "slug",
    "name",
    "description",
    "provisioner",
    "documentation"
  ]
}

=== acasi-ctf/ctf/challenges/games/challenges/prize/challenge.json
{
  "$schema": "../../../schemas/challenge.schema.json",
  "id": "e0867c69-92cd-4e50-b23b-b782ec3e251f",
  "slug": "prize",
  "name": "prize",
  "description": "Game of prize",
  "provisioner": {
    "type": "kubernetes"
  },
  "documentation": [
    {
      "name": "Prize",
      "path": "docs/DoorGame.md"
    }
  ]
}

=== acasi-ctf/ctf/challenges/games/challenges/seven-up/challenge.json
{
  "$schema": "../../../schemas/challenge.schema.json",
  "id": "e0867c69-92cd-4e50-b23b-b782ec3e251f",
  "slug": "seven-up",
  "name": "Seven Up",
  "description": "Game of Seven Up",
  "provisioner": {
    "type": "kubernetes"
  },
  "documentation": [
    {
      "name": "SevenUp",
      "path": "docs/SevenUp.md"
    }
  ]
}

=== acasi-ctf/ctf/challenges/ciphers/challenges/morse-code/challenge.json
{
  "$schema": "../../../schemas/challenge.schema.json",
  "id": "46e5c752-94d8-404d-9ab9-97d0655d1df3",
  "slug": "morse-code",
  "name": "Morse code",
  "description": "This is a challenge that demonstrates morse code cipher",
  "provisioner": {
    "type": "kubernetes"
  },
  "documentation": [
    {
      "name": "Cryptography",
      "path": "docs/1-Cryptography.md"
    },
    {
      "name": "Morse code",
      "path": "docs/Morse_code.md"
    }
  ]
}

=== acasi-ctf/ctf/challenges/games/challenges/noughts/challenge.json
{
  "$schema": "../../../schemas/challenge.schema.json",
  "id": "24477f75-fe6e-4037-9c31-148e13c77d50",
  "slug": "noughts",
  "name": "Noughts",
  "description": "Game of Noughts",
  "provisioner": {
    "type": "kubernetes"
  },
  "documentation": [
    {
      "name": "Noughts",
      "path": "docs/Noughts.md"
    },
    {
     "name": "Code",
      "path": "docs/Code.md"
    }
  ]
}

=== acasi-ctf/ctf/challenges/games/challenges/naught/challenge.json
{
  "$schema": "../../../schemas/challenge.schema.json",
  "id": "e0867c69-92cd-4e50-b23b-b782ec3e251f",
  "slug": "Noughts",
  "name": "Noughts",
  "description": "Game of Noughts",
  "provisioner": {
    "type": "kubernetes"
  },
  "documentation": [
    {
      "name": "Noughts",
      "path": "docs/Noughts.md"
    }
  ]
}

=== acasi-ctf/ctf/challenges/pentesting/challenges/hash-identifier/challenge.json
{
  "$schema": "../../../schemas/challenge.schema.json",
  "id": "5355ab07-eeba-4565-9fc3-0014c389b0ed",
  "slug": "hash-identifier",
  "name": "hash-identifier",
  "description": "This is a challenge that demonstrates hash-identifier tool",
  "provisioner": {
    "type": "kubernetes"
  },
  "documentation": [
    {
      "name": "HashIdentDocumentation",
      "path": "docs/HashIdentDocumentation.md"
    }
  ]
}
