=== acasi-ctf/ctf/challenges/base/challenge-set.schema.json
{
  "$id": "challenge-set-schema",
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "challenge-set",
  "description": "Describes a set of challenges",
  "properties": {
    "$schema": {
    },
    "id": {
      "description": "UUID for this challenge, must be unique amongst other challenge sets",
      "type": "string",
      "format": "uuid",
      "pattern": "^[0-9a-fA-F]{8}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{12}$"
    },
    "slug": {
      "description": "URL-friendly name for this challenge, must be unique amongst other challenge sets",
      "type": "string",
      "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
    },
    "name": {
      "description": "Human-facing name of the challenge set",
      "type": "string"
    },
    "description": {
      "description": "Human-facing description of the challenge set",
      "type": "string"
    },
    "version": {
      "description": "Version number for this challenge set, should be incremented upon releases or changes",
      "type": "string"
    },
    "challenges": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "id",
    "slug",
    "name",
    "description",
    "version",
    "challenges"
  ]
}

=== acasi-ctf/ctf/challenges/games/challenge-set.json
{
  "$schema": "../schemas/challenge-set.schema.json",
  "id": "ac17eea4-853d-4aa3-bf60-3e4800c03b32",
  "slug": "games",
  "name": "Games",
  "description": "Challenge set that contains games",
  "version": "0.1.0",
  "challenges": [
    "yahtzee",
    "seven-up",
    "rock-paper-scissors",
    "prize",
    "noughts"
  ]
}

=== acasi-ctf/ctf/challenges/pentesting/challenge-set.json
{
  "$schema": "../schemas/challenge-set.schema.json",
  "id": "4040a75a-037c-44c0-b1e2-bdcc6ceaddb0",
  "slug": "pentesting",
  "name": "Penetration Testing",
  "description": "Challenge set that focuses on Penetration Testing Utilities",
  "version": "0.1.0",
  "challenges": [
    "strings",
    "binwalk",
    "hash-identifier"
  ]
}

=== acasi-ctf/ctf/challenges/example/challenge-set.json
{
  "$schema": "../schemas/challenge-set.schema.json",
  "id": "d59f2c81-39fe-4e8c-8a7a-427041758a1d",
  "slug": "example",
  "name": "Example challenge set",
  "description": "Example challenge set to be used for reference while developing new challenge sets",
  "version": "0.1.0",
  "challenges": [
    "basic-env-example"
  ]
}

=== acasi-ctf/ctf/challenges/ciphers/challenge-set.json
{
  "$schema": "../schemas/challenge-set.schema.json",
  "id": "bb98d361-b2e0-4324-b2d7-a7a9d603c9e9",
  "slug": "ciphers",
  "name": "Ciphers",
  "description": "Challenge set that focuses on ciphers",
  "version": "0.1.0",
  "challenges": [
    "reverse-cipher",
    "letter-to-number",
    "caesar-cipher",
    "morse-code",
    "comprehensive-challenge"
  ]
}
